export const DEFAULT_FILTERS = {
    convention: {
        'I/2019': true,
        'II/2018': false,
        'I/2018': false,
        'IV/2017': false,
        'II/2017': false,
        'I/2017': false,
        'III/2016': false,
        'I/2016': false,
        'II/2015': false,
        'I/2015': false,
        'II/2014': false,
        'I/2014': false,
        'I/2013': false
    },
    section: {
        'Arbeit / Wirtschaft': false,
        'Bauen / Wohnen / Stadtentwicklung': false,
        'Bildung': false,
        'Mobilität': false,
        'Inneres / Recht': false,
        'Gesundheit': false,
        'Flüchtlings- / Asylpolitik': false,
        'Organisationspolitik': false,
        'Soziales': false,
        'Gleichstellung': false,
        'Initiativanträge': false,
        'Europa': false,
        'Organisation': false,
        'Finanzen': false,
        'Wahlen': false,
        'Statuten- und Richtlinienänderungen': false,
        'Familie / Kinder / Jugend': false,
        'Inneres': false,
        'Umwelt / Energie': false,
        'Internationales': false,
        'Kultur': false,
        'Digital / Medien / Datenschutz': false,
        'Inneres/Verwaltung': false,
    },
    submitters: {
        'Jusos LDK': false,
        'KDV Friedrichshain-Kreuzberg': false,
        'KDV Mitte': false,
        'KDV Spandau': false,
        'KDV Lichtenberg': false,
        'KDV Charlottenburg-Wilmersdorf': false,
        'KDV Neukölln': false,
        'KDV Steglitz-Zehlendorf': false,
        'KDV Marzahn-Hellersdorf': false,
        'KDV Pankow': false,
        'KDV Tempelhof-Schöneberg': false,
        'KDV Reinickendorf': false,
        'KDV Treptow-Köpenick': false
    },
    status: {
        'accepted': false,
        'rejected': false,
        'not_voted': false,
        'dismissed': false,
        'referred': false
    },
    referred: {
        'AH Fraktion': false,
        'Senat': false,
        'Landesvorstand': false,
        'Landesgruppe': false,
        'Parteivorstand': false,
        'BT-Fraktion': false
    }
};
